module Utils.ConfigGenerated exposing (staticConfig)

{-| Generated configuration module from build-time JSON
This module is automatically generated from /config/equipment-defaults.json
DO NOT EDIT THIS FILE MANUALLY - it will be overwritten at build time
-}

-- TYPE ALIASES (to avoid circular imports)


type alias Config =
    { version : String
    , defaults : Defaults
    , fleetLimits : FleetLimits
    , validation : ValidationRules
    }


type alias Defaults =
    { excavators : List ExcavatorDefaults
    , trucks : List TruckDefaults
    , project : ProjectDefaults
    }


type alias ExcavatorDefaults =
    { bucketCapacity : Float
    , cycleTime : Float
    , name : String
    }


type alias TruckDefaults =
    { capacity : Float
    , roundTripTime : Float
    , name : String
    }


type alias ProjectDefaults =
    { workHoursPerDay : Float
    , pondLength : Float
    , pondWidth : Float
    , pondDepth : Float
    }


type alias FleetLimits =
    { maxExcavators : Int
    , maxTrucks : Int
    }


type alias ValidationRules =
    { excavatorCapacity : ValidationRange
    , cycleTime : ValidationRange
    , truckCapacity : ValidationRange
    , roundTripTime : ValidationRange
    , workHours : ValidationRange
    , pondDimensions : ValidationRange
    }


type alias ValidationRange =
    { min : Float
    , max : Float
    }



-- STATIC CONFIGURATION


{-| Static configuration loaded at build time from JSON
-}
staticConfig : Config
staticConfig =
    { version = "1.0.0"
    , defaults = staticDefaults
    , fleetLimits = staticFleetLimits
    , validation = staticValidationRules
    }


staticDefaults : Defaults
staticDefaults =
    { excavators = staticExcavators
    , trucks = staticTrucks
    , project = staticProject
    }


staticExcavators : List ExcavatorDefaults
staticExcavators =
    [ { bucketCapacity = 2.5
      , cycleTime = 2
      , name = "CAT 320 Excavator"
      }
    ]


staticTrucks : List TruckDefaults
staticTrucks =
    [ { capacity = 12
      , roundTripTime = 15
      , name = "Standard Dump Truck"
      }
    ]


staticProject : ProjectDefaults
staticProject =
    { workHoursPerDay = 8
    , pondLength = 40
    , pondWidth = 25
    , pondDepth = 5
    }


staticFleetLimits : FleetLimits
staticFleetLimits =
    { maxExcavators = 10
    , maxTrucks = 20
    }


staticValidationRules : ValidationRules
staticValidationRules =
    { excavatorCapacity = { min = 0.5, max = 15 }
    , cycleTime = { min = 0.5, max = 10 }
    , truckCapacity = { min = 5, max = 30 }
    , roundTripTime = { min = 5, max = 60 }
    , workHours = { min = 1, max = 16 }
    , pondDimensions = { min = 1, max = 1000 }
    }
